In [1]:
# for regression proplem
import pandas as pd 
import numpy as np 

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [9]:
def initialize_parameters(layer_dies): 
    np.random.seed(3) 
    parameter ={}
    L=len(layer_dies)
    for i in range(1,L): 
        parameter['W'+ str(i)] = np.ones((layer_dies[i-1],layer_dies[i]))*0.1 
        parameter['b' + str(i)]=np.zeros((layer_dies[i],1))

    return parameter 

In [10]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [11]:
def liner_forword(A_pre,W,b) : # tell me about the Output of layers
    Z=np.dot(W.T,A_pre) # preves layer outuput === A_pre
    return Z

In [31]:
def L_layers_forward(X,parameters):  # it will make forword propogation for me
    A=X 
    L=len(parameters)//2
    for l in range(1,L+1): 
        A_prev =A 
        W1=parameters['W'+str(l)]
        b1=parameters['b'+str(l)]
        print("A"+str(l-1)+": ",A_prev)
        print("W"+str(l)+": ",W1)
        print("b"+str(l)+": ",b1)
        print("--"*20)

        A=liner_forword(A_prev,W1,b1) # calulating the weigth for give data 
        print("A"+str(l)+": ",A)
        print("***"*20)

    return A,A_prev
        


In [27]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])

In [28]:
X # first student values

array([[8],
       [8]], dtype=int64)

In [29]:
y # output of sencond student 


4

In [32]:
L_layers_forward(X,parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
************************************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
************************************************************


(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [33]:
(y-0.32)**2

13.5424

In [37]:
# update the loss manully for data 

def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [39]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layers_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
************************************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
************************************************************


{'W1': array([[0.09971571, 0.09971571],
        [0.09971571, 0.09971571]]),
 'b1': array([[-3.55360113e-05],
        [-3.55360113e-05]]),
 'W2': array([[0.1005888],
        [0.1005888]]),
 'b2': array([[0.1009568]])}

In [40]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layers_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[7]
 [9]]
W1:  [[0.09971571 0.09971571]
 [0.09971571 0.09971571]]
b1:  [[-3.55360113e-05]
 [-3.55360113e-05]]
----------------------------------------
A1:  [[1.59545139]
 [1.59545139]]
************************************************************
A1:  [[1.59545139]
 [1.59545139]]
W2:  [[0.1005888]
 [0.1005888]]
b2:  [[0.1009568]]
----------------------------------------
A2:  [[0.32096908]]
************************************************************


{'W1': array([[0.0994004 , 0.09931031],
        [0.0994004 , 0.09931031]]),
 'b1': array([[-8.05810157e-05],
        [-8.05810157e-05]]),
 'W2': array([[0.10133532],
        [0.10133532]]),
 'b2': array([[0.10180322]])}

In [41]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layers_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[7]
 [9]]
W1:  [[0.0994004  0.09931031]
 [0.0994004  0.09931031]]
b1:  [[-8.05810157e-05]
 [-8.05810157e-05]]
----------------------------------------
A1:  [[1.59040635]
 [1.58896491]]
************************************************************
A1:  [[1.59040635]
 [1.58896491]]
W2:  [[0.10133532]
 [0.10133532]]
b2:  [[0.10180322]]
----------------------------------------
A2:  [[0.32218259]]
************************************************************


{'W1': array([[0.09901885, 0.09881974],
        [0.09902013, 0.09882139]]),
 'b1': array([[-0.00013509],
        [-0.00013491]]),
 'W2': array([[0.10223832],
        [0.1022375 ]]),
 'b2': array([[0.10280528]])}

In [42]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layers_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[7]
 [9]]
W1:  [[0.09901885 0.09881974]
 [0.09902013 0.09882139]]
b1:  [[-0.00013509]
 [-0.00013491]]
----------------------------------------
A1:  [[1.58431305]
 [1.58113067]]
************************************************************
A1:  [[1.58431305]
 [1.58113067]]
W2:  [[0.10223832]
 [0.1022375 ]]
b2:  [[0.10280528]]
----------------------------------------
A2:  [[0.32362836]]
************************************************************


{'W1': array([[0.09857195, 0.09824516],
        [0.09857657, 0.0982511 ]]),
 'b1': array([[-0.00019893],
        [-0.00019827]]),
 'W2': array([[0.10329607],
        [0.10329312]]),
 'b2': array([[0.10396076]])}

In [44]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layers_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
************************************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
************************************************************
A0:  [[7]
 [9]]
W1:  [[0.09971571 0.09971571]
 [0.09971571 0.09971571]]
b1:  [[-3.55360113e-05]
 [-3.55360113e-05]]
----------------------------------------
A1:  [[1.59545139]
 [1.59545139]]
************************************************************
A1:  [[1.59545139]
 [1.59545139]]
W2:  [[0.1005888]
 [0.1005888]]
b2:  [[0.1009568]]
----------------------------------------
A2:  [[0.32096908]]
************************************************************
A0:  [[ 6]
 [10]]
W1:  [[0.0994004  0.09931031]
 [0.0994004  0.09931031]]
b1:  [[-8.05810157e-05]
 [-8.05810157e-05]]
----------------------------------------
A1:  [[1.59040635]
 [1.5889649

{'W1': array([[0.09361196, 0.08943454],
        [0.09404552, 0.09016107]]),
 'b1': array([[-0.00103555],
        [-0.00096477]]),
 'W2': array([[0.11634574],
        [0.11604669]]),
 'b2': array([[0.11671047]])}

In [46]:
import tensorflow 
from tensorflow import keras 
from keras import Sequential 
from keras.layers import Dense

In [48]:
model =Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\raj\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [49]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [50]:
model.get_weights()

[array([[ 1.1382056 , -0.10109782],
        [-0.29946697,  0.9130758 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.21170628],
        [-1.1940728 ]], dtype=float32),
 array([0.], dtype=float32)]

In [52]:
new_wegihts = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32)
               ,np.array([0. , 0. ] , dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32), 
               np.array([0.],dtype=np.float32)]

In [53]:
model.set_weights(new_wegihts)

In [54]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [55]:
optimizer =keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizer)

In [58]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 27.4954
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 29.2391 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 28.0441 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.8191 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31.7344  
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.8644  
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.0921 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.0778 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.9551  
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 27.8269 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.8718 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.3410 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.3215 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.5858 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 28.1533 
Epoch 16/75
4/4 

In [59]:
model.get_weights()

[array([[0.37382805, 0.37382805],
        [0.36589366, 0.36589366]], dtype=float32),
 array([0.27255452, 0.27255452], dtype=float32),
 array([[0.37317064],
        [0.37317064]], dtype=float32),
 array([0.20489334], dtype=float32)]